export const scenarioVersion = 1;
export const browserSaveKey = "rail-scenario-planner:auto-save:v2";

export const defaultScenario = {
  version: scenarioVersion,
  nextId: 20,
  meta: {
    title: "Rail Scenario Planner",
    subtitle: "Explain railway planning, operations, and conflicts",
    author: "Stakeholder Operations Demo",
    notes: "Use this scenario to discuss capacity, conflicts, and operational tradeoffs.",
    theme: "professional",
    colors: {
      accent: "#2563eb",
      path: "#0f766e",
      conflict: "#dc2626",
      label: "#111827",
    },
  },
  exports: {
    playbackDuration: 10,
    playbackFps: 30,
    playbackSpeed: 1,
    resetOnExport: true,
  },
  trackModules: [
    { id: "m1", type: "station", position: [-18, 0, -4], rotation: 0, name: "Central" },
    { id: "m2", type: "straight", position: [-10, 0, -4], rotation: 0 },
    { id: "m3", type: "turnout", position: [-2, 0, -4], rotation: 0, name: "J1" },
    { id: "m4", type: "straight", position: [6, 0, -4], rotation: 0 },
    { id: "m5", type: "station", position: [15, 0, -4], rotation: 0, name: "East Park" },
    { id: "m6", type: "curve", position: [22, 0, 2], rotation: Math.PI * 0.5 },
    { id: "m7", type: "straight", position: [15, 0, 10], rotation: Math.PI },
    { id: "m8", type: "station", position: [5, 0, 10], rotation: Math.PI, name: "Airport Branch" },
    { id: "m9", type: "curve", position: [-6, 0, 6], rotation: Math.PI },
    { id: "m10", type: "straight", position: [-16, 0, 10], rotation: Math.PI },
    { id: "m11", type: "curve", position: [-24, 0, 2], rotation: Math.PI * 1.5 },
    { id: "m12", type: "signal", position: [-6, 0, -7], rotation: 0, name: "S12" },
    { id: "m13", type: "signal", position: [9, 0, -7], rotation: 0, name: "S18" },
  ],
  connections: [
    { fromModuleId: "m1", fromPortId: "B", toModuleId: "m2", toPortId: "A" },
    { fromModuleId: "m2", fromPortId: "B", toModuleId: "m3", toPortId: "A" },
    { fromModuleId: "m3", fromPortId: "B", toModuleId: "m4", toPortId: "A" },
    { fromModuleId: "m4", fromPortId: "B", toModuleId: "m5", toPortId: "A" },
    { fromModuleId: "m5", fromPortId: "B", toModuleId: "m6", toPortId: "A" },
    { fromModuleId: "m6", fromPortId: "B", toModuleId: "m7", toPortId: "A" },
    { fromModuleId: "m7", fromPortId: "B", toModuleId: "m8", toPortId: "A" },
    { fromModuleId: "m9", fromPortId: "B", toModuleId: "m10", toPortId: "A" },
    { fromModuleId: "m10", fromPortId: "B", toModuleId: "m11", toPortId: "A" },
  ],
  trains: [
    {
      id: "t1",
      displayName: "IC-214",
      color: "#2563eb",
      route: "main",
      selectedRouteId: "main",
      speed: 7.2,
      startOffset: 0,
      enabled: true,
    },
    {
      id: "t2",
      displayName: "RE-08",
      color: "#059669",
      route: "main",
      selectedRouteId: "main",
      speed: 6.1,
      startOffset: 0.34,
      enabled: true,
    },
    {
      id: "t3",
      displayName: "FR-772",
      color: "#9333ea",
      route: "branch",
      selectedRouteId: "branch",
      speed: 5.2,
      startOffset: 0.18,
      enabled: true,
    },
  ],
  conflicts: [
    {
      id: "c1",
      type: "junction",
      severity: "high",
      position: [-2, 0, -4],
      affectedModuleIds: ["m3"],
      affectedTrainIds: ["t1", "t2"],
      label: "Junction J1 crossing move",
      active: true,
    },
    {
      id: "c2",
      type: "platform",
      severity: "medium",
      position: [15, 0, -4],
      affectedModuleIds: ["m5"],
      affectedTrainIds: ["t2"],
      label: "Platform 2 occupied",
      active: true,
    },
    {
      id: "c3",
      type: "blocked",
      severity: "high",
      position: [6, 0, -4],
      affectedModuleIds: ["m4"],
      affectedTrainIds: ["t1"],
      label: "Maintenance possession on block B4",
      active: true,
    },
  ],
  view: {
    preset: "overview",
    speed: 1,
    snapEnabled: true,
    presentationMode: false,
    overlays: {
      labels: true,
      conflicts: true,
      blocks: true,
      paths: true,
      connections: true,
      validation: true,
    },
  },
};
