export const colors = {
  ground: 0xf4f7fa,
  grid: 0xc7d2de,
  rail: 0x334155,
  sleeper: 0x8b9aaa,
  ballast: 0xd6dee8,
  platform: 0xcbd5e1,
  platformEdge: 0xf59e0b,
  station: 0x1f4b76,
  signalRed: 0xdc2626,
  signalGreen: 0x059669,
  signalMast: 0x475569,
  occupied: 0x2563eb,
  path: 0x0f766e,
  conflictLow: 0xf59e0b,
  conflictHigh: 0xdc2626,
  selection: 0x38bdf8,
  connection: 0x10b981,
  validation: 0xef4444,
  snapGrid: 0xf59e0b,
};

export function createMaterials(THREE) {
  return {
    ground: new THREE.MeshStandardMaterial({ color: colors.ground, roughness: 0.86, metalness: 0.01 }),
    grid: new THREE.LineBasicMaterial({ color: colors.grid, transparent: true, opacity: 0.72 }),
    rail: new THREE.MeshStandardMaterial({ color: colors.rail, roughness: 0.36, metalness: 0.28 }),
    sleeper: new THREE.MeshStandardMaterial({ color: colors.sleeper, roughness: 0.76, metalness: 0.02 }),
    ballast: new THREE.MeshStandardMaterial({ color: colors.ballast, roughness: 0.88, metalness: 0 }),
    platform: new THREE.MeshStandardMaterial({ color: colors.platform, roughness: 0.82, metalness: 0.02 }),
    platformEdge: new THREE.MeshStandardMaterial({ color: colors.platformEdge, roughness: 0.54, metalness: 0.02 }),
    station: new THREE.MeshStandardMaterial({ color: colors.station, roughness: 0.58, metalness: 0.05 }),
    signalMast: new THREE.MeshStandardMaterial({ color: colors.signalMast, roughness: 0.46, metalness: 0.18 }),
    signalRed: new THREE.MeshStandardMaterial({
      color: colors.signalRed,
      emissive: colors.signalRed,
      emissiveIntensity: 0.5,
      roughness: 0.34,
    }),
    signalGreen: new THREE.MeshStandardMaterial({
      color: colors.signalGreen,
      emissive: colors.signalGreen,
      emissiveIntensity: 0.42,
      roughness: 0.34,
    }),
    occupied: new THREE.MeshBasicMaterial({
      color: colors.occupied,
      transparent: true,
      opacity: 0.2,
      depthWrite: false,
      side: THREE.DoubleSide,
    }),
    path: new THREE.LineBasicMaterial({ color: colors.path, transparent: true, opacity: 0.7 }),
    selection: new THREE.MeshBasicMaterial({
      color: colors.selection,
      transparent: true,
      opacity: 0.28,
      depthWrite: false,
      side: THREE.DoubleSide,
    }),
    connection: new THREE.MeshBasicMaterial({
      color: colors.connection,
      transparent: true,
      opacity: 0.82,
      depthWrite: false,
    }),
    validation: new THREE.MeshBasicMaterial({
      color: colors.validation,
      transparent: true,
      opacity: 0.78,
      depthWrite: false,
    }),
    previewValid: new THREE.MeshBasicMaterial({
      color: colors.connection,
      transparent: true,
      opacity: 0.32,
      depthWrite: false,
      side: THREE.DoubleSide,
    }),
    previewGrid: new THREE.MeshBasicMaterial({
      color: colors.snapGrid,
      transparent: true,
      opacity: 0.28,
      depthWrite: false,
      side: THREE.DoubleSide,
    }),
    previewBlocked: new THREE.MeshBasicMaterial({
      color: colors.validation,
      transparent: true,
      opacity: 0.3,
      depthWrite: false,
      side: THREE.DoubleSide,
    }),
  };
}
